// Automatically generated by ./configure 
#pragma once
// gcc
#define WITH_GCC 1
// pkgconfig
#define WITH_PKGCONFIG 1
// install
#define WITH_INSTALL 1
// gitversion
#define GITVERSION "0.9-10-gaf2cc9"
